# Generated by Django 2.2.4 on 2020-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('d_no', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_contactno', models.IntegerField(unique=True)),
                ('d_specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('p_contactno', models.IntegerField(unique=True)),
                ('p_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctors')),
                ('paitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
    ]
