# Generated by Django 2.2.4 on 2020-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userregistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_contactno', models.IntegerField(unique=True)),
                ('user_address', models.CharField(max_length=40)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
